---
- name: setup Mysql with nopcommerce db and remote login
  become: yes
  hosts: all #db
  tasks:
    - name: Installing Mysql  and dependencies
      package:
         name: "{{item}}"
         state: present
         update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
       become: yes
    - name: start and enable mysql service
      service:
         name: mysql
         state: started
         enabled: yes

    - name: creating mysql user (test)
      mysql_user:
         name: test
         password: P@ssw0rd
         priv: '*.*:ALL'
         host: '%'
         state: present
    
    - name: creating nop DB
      mysql_db:
         name: nop
         state: present
    
    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted