---
- hosts: all

  tasks:
  - name: Update APT package manager 
    become: true
    apt:
      update_cache: yes

  - name: Install OpenJDK-11-jdk
    become: yes
    apt:
      name: openjdk-11-jdk
      state: present
