---
- name: Install Apache Tomcat9 using ansible
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
 
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
 
    - name: Copy Tomcat service from local to remote
      copy:
        src: /etc/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
 
    - name: Start and Enable Tomcat 9 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true