---
- hosts: all
  become: true
  tasks:
  -
    apt:
      name: nginx
      state: latest
      update_cache: true
    name: "Update apt cache and Install nginx"
  -
    name: "Start service nginx"
    service:
      name: nginx
      state: started
