---
- hosts: 172.31.85.175 #web
  tasks:
  - name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/www/nopCommerce450
    state: directory
    mode: '0755'
  - name: Download nopCommerce_4.50.2_NoSource_linux_x64.zip
    get_url:
      url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
     dest: /var/www/nopCommerce450
  - name: Install unzip
    apt: 
    name: unzip 
    become: true
    state: present

 - name: Extract nopCommerce_4.50.2_NoSource_linux_x64.zip
  ansible.builtin.unarchive:
    src: nopCommerce_4.50.2_NoSource_linux_x64.zip
    dest: /var/www/nopcoomerce450
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/www/nopCommerce450/bin
    state: directory
    mode: '0755'
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/www/nopCommerce450/logs
    state: directory
    mode: '0755'
    